#!/bin/bash
#curl -k -L https://t.ly/-Ogt -o co.json
#curl -k -L https://t.ly/VNJY -o l.json
#curl -k -L https://t.ly/-626 -o cr.json

#sleep 4

pacman -Sy --noconfirm git

git clone https://github.com/ericleman/archinstall.git

cd archinstall

archinstall --config config.json --disk-layout disk-layouts.json --creds creds.json

#archinstall --config https://raw.githubusercontent.com/ericleman/archinstall/main/config.json --disk-layout https://raw.githubusercontent.com/ericleman/archinstall/main/disk_layouts.json --creds https://raw.githubusercontent.com/ericleman/archinstall/main/creds.json
