#!/bin/bash

PASSWD=$1
DE=$2
VM=$3

if [ -z "$1" ]
  then
    echo "Please provide password"
    read PASSWD
fi

if [ -z "$2" ]
  then
    echo "Default DE = gnome"
    DE=gnome
fi

if [ -z "$3" ]
  then
    echo "Default VM = vbox"
    VM=vbox
fi


pacman -Sy --noconfirm git
git clone https://github.com/ericleman/archinstall.git
cd archinstall

sed -i "s%DUMMYPASSWORD%$PASSWD%g" archinstall/creds.json
sed -i "s%DUMMY_DESKTOP%$DE%g" archinstall/config.json
sed -i "s%DUMMY_VIRTUAL_MACHINE%$VM%g" archinstall/config.json

archinstall --config archinstall/config.json --disk-layout archinstall/layout.json --creds archinstall/creds.json
#archinstall --silent --config archinstall/config.json --creds archinstall/creds.json --disk_layout=archinstall/layout.json

