#!/bin/bash

DE=gnome

pacman -Sy --noconfirm git
git clone https://github.com/ericleman/archinstall.git
cd archinstall

sed -i "s%DUMMYPASSWORD%$1%g" $DE/archinstall/creds.json
archinstall --config $DE/archinstall/config.json --disk-layout $DE/archinstall/layout.json --creds $DE/archinstall/creds.json

