- name: install vbox related packages
  pacman:
    name:
      - virtualbox-guest-utils 
    state: present

- name: enable Vbox service
  ansible.builtin.systemd:
    name: vboxservice
    enabled: yes

- name: Add the user to vbox group
  ansible.builtin.user:
    name: eric
    groups: vboxsf
    append: yes
