- name: install Gnome related packages
  pacman:
    name:
      - plasma
      - xf86-input-vmmouse # as we might use Xorg as Wayland fallback
      - xf86-video-vmware # as we might use Xorg as Wayland fallback
    state: present

- name: enable SDDM service
  ansible.builtin.systemd:
    name: sddm
    enabled: yes

- name: auto login
  copy:
    src: personal/etc/sddm.conf.d
    dest: /etc/
    mode: u+rwx,g+r,o--
