- name: install Gnome related packages
  pacman:
    name:
      - plasma
      - kde-system-meta
      - xf86-input-vmmouse # as we might use Xorg as Wayland fallback
      - xf86-video-vmware # as we might use Xorg as Wayland fallback
    state: present

- name: enable SDDM service
  ansible.builtin.systemd:
    name: sddm
    enabled: yes

- name: auto login
  copy:
    src: personal/etc/sddm.conf.d
    dest: /etc/
    mode: u+rwx,g+r,o--

- name: copy paste functions (bug on KDE on VMWARE https://github.com/vmware/open-vm-tools/issues/568)
  copy:
    src: personal/etc/xdg/startkderc
    dest: /etc/xdg/startkderc
    mode: '0755'
  when: vm == "vmware"

# Configuration
- name: scaling factor
  ansible.builtin.command: kwriteconfig5 --file ~/.config/kdeglobals --group KScreen --key ScaleFactor 1.25
  become: yes
  become_user: eric

- name: scaling factor
  ansible.builtin.command: kwriteconfig5 --file ~/.config/kcmfonts --group General --key forceFontDPI 120
  become: yes
  become_user: eric

- name: hidden files
  ansible.builtin.command: kwriteconfig5 --file ~/.config/kdeglobals --group "KFileDialog Settings" --key "Show hidden files" true
  become: yes
  become_user: eric

- name: panel height
  ansible.builtin.command: kwriteconfig5 --file ~/.config/plasmashellrc --group "PlasmaViews" --group "Panel 2" --group "Defaults" --key "thickness" 48
  become: yes
  become_user: eric

- name: Meta key opens Overview
  ansible.builtin.command: kwriteconfig5 --file kwinrc --group ModifierOnlyShortcuts --key Meta "org.kde.kglobalaccel,/component/kwin,,invokeShortcut,Overview"
  become: yes
  become_user: eric

