- name: install KDE related packages
  pacman:
    name:
      - plasma
      - kde-system-meta
      - kde-utilities-meta
      - xf86-input-vmmouse # as we might use Xorg as Wayland fallback
      - xf86-video-vmware # as we might use Xorg as Wayland fallback
#      - kvantum # theming engine
    state: present

- name: enable SDDM service
  ansible.builtin.systemd:
    name: sddm
    enabled: yes

- name: auto login
  copy:
    src: personal/etc/sddm.conf.d
    dest: /etc/
    mode: u+rwx,g+r,o--

- name: copy paste functions (bug on KDE on VMWARE https://github.com/vmware/open-vm-tools/issues/568)
  copy:
    src: personal/etc/xdg/startkderc
    dest: /etc/xdg/startkderc
    mode: '0755'
  when: vm == "vmware"

# Configuration
- name: Copy some files to .config
  copy:
    src: personal/home/.config/{{ item }}
    dest: /home/eric/.config/
    owner: "eric"
    group: "eric"
    mode: u+rwx,g+r,o--
  with_items:
    - breezerc
    - dolphinrc
    - filetypesrc
    - kcmfonts
    - kcminputrc
    - kdeglobals
    - kglobalshortcutsrc
    - khotkeysrc
    - kscreenlockerrc
    - kwinrc
    - kwinrulesrc
    - mimeapps.list
    - plasma-org.kde.plasma.desktop-appletsrc
    - plasmarc
    - plasmashellrc
    - systemsettingsrc
    - Trolltech.conf



- name: install breeze-enhanced (alternative is https://github.com/paulmcauley/klassy)
  aur:
    use: yay
    name:
      - breeze-enhanced-git
  become: yes
  become_user: eric

- name: Copy Kwin Force Blur script (I inspired from https://userbase.kde.org/Tutorials/Force_Transparency_And_Blur but use force blur instead)
  copy:
    src: personal/home/.local/share/kwin
    dest: /home/eric/.local/share/
    owner: "eric"
    group: "eric"
    mode: u+rwx,g+r,o--          




# 3 items below are an attempt to create a custom theme. But I can remove it for now
# - name: Copy Kvantum
#   copy:
#     src: personal/home/.config/Kvantum
#     dest: /home/eric/.config/
#     owner: "eric"
#     group: "eric"
#     mode: u+rwx,g+r,o--          

# - name: Copy Aurorae
#   copy:
#     src: personal/home/.local/share/aurorae
#     dest: /home/eric/.local/share/
#     owner: "eric"
#     group: "eric"
#     mode: u+rwx,g+r,o--          

# - name: Copy Plasma desktop theme
#   copy:
#     src: personal/home/.local/share/plasma
#     dest: /home/eric/.local/share/
#     owner: "eric"
#     group: "eric"
#     mode: u+rwx,g+r,o--          



###################################################################################################################################################
# - name: scaling factor
#   ansible.builtin.command: kwriteconfig5 --file ~/.config/kdeglobals --group KScreen --key ScaleFactor 1.25
#   become: yes
#   become_user: eric

# - name: scaling factor
#   ansible.builtin.command: kwriteconfig5 --file ~/.config/kcmfonts --group General --key forceFontDPI 120
#   become: yes
#   become_user: eric

# - name: hidden files
#   ansible.builtin.command: kwriteconfig5 --file ~/.config/kdeglobals --group "KFileDialog Settings" --key "Show hidden files" true
#   become: yes
#   become_user: eric

# - name: panel height
#   ansible.builtin.command: kwriteconfig5 --file ~/.config/plasmashellrc --group "PlasmaViews" --group "Panel 2" --group "Defaults" --key "thickness" 48
#   become: yes
#   become_user: eric

# - name: Meta key opens Overview
#   ansible.builtin.command: kwriteconfig5 --file kwinrc --group ModifierOnlyShortcuts --key Meta "org.kde.kglobalaccel,/component/kwin,,invokeShortcut,Overview"
#   become: yes
#   become_user: eric

