- hosts: localhost
  become: true

  tasks:
  - name: ERIC (sudo nopasswd, home directories...)
    include_tasks: 010-eric-setup.yaml

  - name: Virtualmachine stuff
    include_tasks: 010-vm.yaml

  - name: Developper Apps Install 
    include_tasks: 020-core-apps.yaml

  - name: X Windows Install 
    include_tasks: 030-xorg.yaml

  - name: LightDM Install 
    include_tasks: 040-lightdm.yaml

  - name: BSPWM Install 
    include_tasks: 050-bspwm.yaml

  - name: Rofi Install 
    include_tasks: 060-rofi.yaml

  - name: Network Manager Dmenu Install (used with Rofi)
    include_tasks: 061-networkmanager-dmenu.yaml

  - name: Conky Apps Install ## TO DO
    include_tasks: 070-conky.yaml

  - name: Picom Install ## TO DO
    include_tasks: 080-picom.yaml

  - name: Kitty Apps Install 
    include_tasks: 090-kitty.yaml

  - name: Thunar Apps Install 
    include_tasks: 100-thunar.yaml

  - name: Polybar Apps Install ## TO DO
    include_tasks: 110-polybar.yaml

  - name: Zsh Apps Install ## DONE
    include_tasks: 120-zsh.yaml

  - name: Feh Install ## DONE
    include_tasks: 130-feh.yaml

  - name: Dunst Install ## DONE
    include_tasks: 140-dunst.yaml

  - name: Global Theme ## DONE
    include_tasks: 150-theme.yaml

  - name: Gedit 
    include_tasks: 160-gedit.yaml

  - name: Polkit
    include_tasks: 170-polkit.yaml

  - name: Pamac
    include_tasks: 180-pamac.yaml
