- hosts: localhost
  become: true

  tasks:
  - name: ERIC (sudo nopasswd, home directories...)
    include_tasks: 010-eric-setup.yaml

  - name: X Windows Install 
    include_tasks: 020-xorg.yaml

  - name: LightDM Install 
    include_tasks: 030-lightdm.yaml

  - name: BSPWM Install 
    include_tasks: 040-bspwm.yaml

  - name: Core Apps Install 
    include_tasks: 040-applications.yaml

