- name: install lightDM related packages
  pacman:
    name:
      - lightdm 
      - lightdm-gtk-greeter
      - lightdm-webkit2-greeter
      - lightdm-webkit-theme-litarvan
    state: present

- name: enable LightDM service
  ansible.builtin.systemd:
    name: lightdm
    enabled: yes

- name: auto login
  replace:
    path: /etc/lightdm/lightdm.conf
    regexp: '#autologin-user='
    replace: 'autologin-user=eric'

- name: Ensure group "autologin" exists
  group:
    name: autologin
    state: present

- name: Add the user 'eric' to the autologin's groups
  ansible.builtin.user:
    name: eric
    groups: autologin
    append: yes

- name: greeter session
  replace:
    path: /etc/lightdm/lightdm.conf
    regexp: '#greeter-session=example-gtk-gnome'
    replace: 'greeter-session=lightdm-webkit2-greeter'


- name: define litarvan as theme
  replace:
    path: /etc/lightdm/lightdm-webkit2-greeter.conf
    regexp: 'webkit_theme        = antergos'
    replace: 'webkit_theme        = litarvan'


- name: copy avatar files
  copy:
    src: personal/var/lib/AccountsService/icons/eric.png
    dest: /var/lib/AccountsService/icons/eric.png

- name: copy avatar files 2
  copy:
    src: personal/var/lib/AccountsService/users/eric
    dest: /var/lib/AccountsService/users/eric



#- name: Install theme lightdm-webkit-theme-aether 
#  aur:
#    use: yay
#    name: lightdm-webkit-theme-aether
#  become: yes
#  become_user: eric


