- name: install packages
  pacman:
    name:
      - kitty
    state: present

- name: Copy theme
  copy:
    src: personal/home/.config/kitty
    dest: /home/eric/.config
    owner: "eric"
    group: "eric"
    mode: u+rwx,g+r,o--          

- name: Create a symbolic link from xterm to kitty as most CLI app (ranger, vim...) will open gnome-terminal or xterm by default on gnome. # see https://www.reddit.com/r/Alacritty/comments/hecdqv/changing_default_terminal_to_alacritty_in_gnome/
  ansible.builtin.file:
    src: /usr/bin/kitty
    dest: /usr/bin/xterm
    state: link
    mode: '1777'
