- name: Copy extension1
  copy:
    src: personal/home/.local/share/gnome-shell/extensions/extension1@ericleman.com
    dest: /home/eric/.local/share/gnome-shell/extensions/
    owner: "eric"
    group: "eric"
    mode: u+rwx,g+r,o--          


- name: Enable extension1
  ansible.builtin.shell: gnome-extensions enable extension1@ericleman.com
  become: yes
  become_user: eric



