- name: change Wayland to false if on virtualbox
  replace:
    path: /etc/gdm/custom.conf
    regexp: '#WaylandEnable=false'
    replace: 'WaylandEnable=false'
  when: vm == "vbox"

- name: auto login
  lineinfile:
    path: /etc/gdm/custom.conf
    regexp: '\[daemon\] '
    insertafter: '\[daemon\]'
    state: present
    line: "{{ item }}"
  with_items:
  - 'AutomaticLogin=eric'
  - 'AutomaticLoginEnable=True'

