- hosts: localhost
  become: true

  tasks:
  - name: ERIC (sudo nopasswd, home directories...)
    include_tasks: 010-eric-setup.yaml

  - name: Virtualmachine stuff
    include_tasks: 010-vm.yaml

  - name: Developper Apps Install 
    include_tasks: 020-core-apps.yaml

  - name: Gnome Shell and GDM
    include_tasks: 030-gnome.yaml

  - name: Alacritty Apps Install 
    include_tasks: 090-alacritty.yaml

  - name: Ranger Install 
    include_tasks: 100-ranger.yaml

  - name: Zsh Apps Install ## DONE
    include_tasks: 120-zsh.yaml

  - name: VS Code
    include_tasks: 160-code.yaml

  - name: btop
    include_tasks: 190-btop.yaml

  - name: Chrome
    include_tasks: 300-chrome.yaml

  - name: HP Printer
    include_tasks: 310-hp-printer.yaml

  - name: Wifi dongle
    include_tasks: 320-wifi-dongle.yaml

  - name: LibreOffice
    include_tasks: 330-libreoffice.yaml

  - name: My Gnome Extensions
    include_tasks: 500-my-extensions.yaml

  - name: Gnome config with dconf
    include_tasks: 510-gnome-config.yaml

