- name: install Gnome related packages
  pacman:
    name:
      - gnome 
      - gdm
      - gnome-tweaks
    state: present

- name: enable GDM service
  ansible.builtin.systemd:
    name: gdm
    enabled: yes
    