- name: Enable pacman colorised output and verbose package lists 
  replace:
    path: /etc/pacman.conf
    regexp: '{{ item.regexp }}'
    replace: '{{ item.replace }}'
  with_items:
    - { regexp: '^#Color$', replace: 'Color' }
    - { regexp: '^#VerbosePkgLists$', replace: 'VerbosePkgLists' }
