- name: install pamac
  aur:
    use: yay
    name:
      - pamac-aur
  become: yes
  become_user: eric
- name: enable AUR
  replace:
    path: /etc/pamac.conf
    regexp: '#EnableAUR'
    replace: 'EnableAUR'
- name: Check AUR Updates
  replace:
    path: /etc/pamac.conf
    regexp: '#CheckAURUpdates'
    replace: 'CheckAURUpdates'

