- hosts: localhost
  become: true

  tasks:
  - name: configure gdm
    block:
    - name: change Wayland to false
      replace:
        path: /etc/gdm/custom.conf
        regexp: '#WaylandEnable=false'
        replace: 'WaylandEnable=false'
    - name: auto login
      lineinfile:
        path: /etc/gdm/custom.conf
        regexp: '\[daemon\] '
        insertafter: '\[daemon\]'
        state: present
        line: "{{ item }}"
      with_items:
      - 'AutomaticLogin=eric'
      - 'AutomaticLoginEnable=True'

  - name: sudo without password
    community.general.sudoers:
      name: no-passwd-eric
      user: eric
      commands: ALL
      nopassword: yes

  - name YAY
    block:
      - name: install GO as it seems to be prerequisite (otherwise crashes)
        pacman:
          name: 
            - go
          state: present        
      - name: install yay
        aur:
          name: yay
          use: makepkg
          state: present 
        become: yes
        become_user: eric

  - name: Install and configure Pamac-aur
    block:
      - name: install pamac
        aur:
          use: yay
          name:
            - pamac-aur
        become: yes
        become_user: eric
      - name: copy config
        copy:
          src: /archinstall/ansible/config/pamac.conf 
          dest: /etc/pamac.conf          

  - name: Enable pacman colorised output and verbose package lists
    replace:
      path: /etc/pacman.conf
      regexp: '{{ item.regexp }}'
      replace: '{{ item.replace }}'
    with_items:
      - { regexp: '^#Color$', replace: 'Color' }
      - { regexp: '^#VerbosePkgLists$', replace: 'VerbosePkgLists' }

  - name: install Neofetch
    block:
      - name: install
        pacman:
          name: 
            - neofetch
          state: present
      - name: configure
        ansible.builtin.lineinfile:
          path: /etc/bash.bashrc
          line: neofetch
          create: yes

  - name: generic Gnome settings
    block:
      - name: psutils is required for dconf
        pacman:
          name: python-psutil
          state: present
      - name: font size
        dconf: key="/org/gnome/desktop/interface/text-scaling-factor" value="1.5"
      - name: maximize and minimize buttons
        dconf: key="/org/gnome/desktop/wm/preferences/button-layout" value="appmenu:minimize,maximize,close"
      - name: Show seconds on clock
        dconf: key="/org.gnome.desktop.interface/clock-show-seconds" value="true"
        
      
