- hosts: localhost
  become: true

  tasks:
  - name: install Vivaldi and optionals
    pacman:
      name: 
        - vivaldi
      state: present 
      
  - name: change Wayland to false
    replace:
      path: /etc/gdm/custom.conf
      regexp: '#WaylandEnable=false'
      replace: 'WaylandEnable=false'

  - name: install yay
    aur:
      name: yay
      use: makepkg
      state: present 
    become: yes
    become_user: eric

    
