#!/bin/sh
## Java Applications
wmname LG3D
export _JAVA_AWT_WM_NONREPARENTING=1

# use VS Code as default Editor
export EDITOR=code

#BSPWM configuration
#bspc config border_radius       8
bspc config border_width         0
bspc config window_gap           20
bspc config top_padding          30
bspc config bottom_padding       5
bspc config left_padding         5
bspc config right_padding        5

bspc config single_monocle       false
#bspc config click_to_focus       true
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc config focus_by_distance    true
bspc config focus_follows_pointer true
#bspc config history_aware_focus  true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

bspc config pointer_motion_interval 5


#BSPWM coloring
bspc config normal_border_color		"#4c566a"
bspc config active_border_color		"#1e1e1e"
bspc config focused_border_color	"#5e81ac"
bspc config presel_feedback_color	"#5e81ac"
#bspc config urgent_border_color 	"#dd2727"


#Single monitor
bspc monitor -d ""

#Dual monitor
#find out names with arandr or xrandr
#bspc monitor DP-2 -d 1 2 3 4 5 6 7 8 9
#bspc monitor LVDS1 -d 1 2 3 4
#bspc monitor DP3 -d  5 6 7 8 9
#bspc monitor HDMI-0 -d 1 2 3 4 5 6 7 8 9 10
#bspc monitor HDMI-1 -d 1 2 3 4 5 6 7 8 9 10
#bspc monitor HDMI1 -d 1 2 3 4 5
#bspc monitor HDMI2 -d 6 7 8 9 10

#Fullscreen applications
bspc rule -a Vlc state=fullscreen

#Floating applications
#bspc rule -a rofi state=floating sticky=on
bspc rule -a Xfce4-terminal state=floating
bspc rule -a com-itfinance-core-Starter state=floating desktop='^7' follow=on

#Tiled applications
bspc rule -a Gnome-disks state=tiled
bspc rule -a Xfce4-settings-manager state=tiled
#bspc rule -a Google-chrome state=tiled desktop='^8' follow=on

#open applications on specific workspaces
#bspc rule -a Firefox desktop='^1' follow=on
#bspc rule -a Google-chrome desktop='^1' follow=on
#bspc rule -a Chromium desktop='^1'  follow=on
#bspc rule -a Subl desktop='^2' follow=on
#bspc rule -a Atom desktop='^2' follow=on
#bspc rule -a Steam desktop='^5'
#bspc rule -a vlc desktop='^6'  follow=on
#bspc rule -a mpv desktop='^6'  follow=on
#bspc rule -a Vivaldi-stable desktop='^6' follow=on
#bspc rule -a Vivaldi-snapshot desktop='^6' follow=on
#bspc rule -a Transmission-gtk desktop='^7' follow=on
#bspc rule -a Thunar desktop='^8' follow=on
#bspc rule -a discord desktop='^9' follow=on
#bspc rule -a Spotify desktop='^10' follow=on


#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DP-1)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI1)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI2)

###External rules
##Pseudo automatic mode: always splits focused window when opening new window
#bspc config external_rules_command ~/.config/bspwm/scripts/pseudo_automatic_mode
##Adjust new window: splits biggest windows to keep windows about the same size
#bspc config external_rules_command ~/.config/bspwm/scripts/adjust-new-window
bspc config external_rules_command ~/.config/bspwm/external_rules.sh

## Autostart -------------------------------------------------#

killall -q sxhkd; sxhkd &
killall -q clipmenud; clipmenud &

#killall -q VBoxClient-all
#VBoxClient-all & #required to enable copy paste on Virtualbox

killall -q vmware-user
vmware-user & #required to enable copy paste on VMWare

# polkit agent
if [[ ! `pidof xfce-polkit` ]]; then
	/usr/lib/xfce-polkit/xfce-polkit &
fi

# Fix cursor
xsetroot -cursor_name left_ptr

# polybar	
$HOME/.config/polybar/launch.sh

killall -q pamac-tray
pamac-tray & #required to enable copy paste on VMWare


## PICOM
# Terminate if picom is already running
killall -q picom
# Wait until the processes have been shut down
while pgrep -u $UID -x picom >/dev/null; do sleep 1; done
# Launch picom
picom --config ~/.config/picom/picom.conf --experimental-backends &

#killall -q feh
#feh --bg-fill /usr/share/backgrounds/nord.jpg &
$HOME/.config/wpg/wp_init.sh

## Super Key
killall -q ksuperkey
ksuperkey -e 'Super_L=Alt_L|F1' &


